language: python
git:
    submodules: false
python:
    - "3.6"
    - "3.7"
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install:
    - pip install -r requirements.txt
script:
    - python -m pytest
